---
abstract: 'perform simple text clustering by key collision'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Fingerprint
requires:
  List::MoreUtils: '0'
  Text::Unidecode: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/creaktive/Text-Fingerprint/issues
  homepage: https://github.com/creaktive/Text-Fingerprint
  repository: git://github.com/creaktive/Text-Fingerprint.git
version: '0.006'
x_contributors:
  - 'Sergey Romanov <sromanov-dev@yandex.ru>'
