---
abstract: 'perform simple text clustering by key collision'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  Test::Requires: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Fingerprint
requires:
  Exporter: 0
  Text::Unidecode: 0
  base: 0
  perl: 5.014
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/Text-Fingerprint/issues
  homepage: https://github.com/creaktive/Text-Fingerprint
  repository: git://github.com/creaktive/Text-Fingerprint.git
version: 0.001
